exports.JavaScriptList = [
  "JavaScript/DOM.md",
  "JavaScript/Web-Storage",
  "JavaScript/airbnb-javascript-style-guide",
  "JavaScript/ajax",
  "JavaScript/array-shuffle",
  "JavaScript/bom",
  "JavaScript/box-javascript-refactoring",
  "JavaScript/browser-compability",
  "JavaScript/call-apply",
  "JavaScript/call-by-sharing",
  "JavaScript/closure",
  "JavaScript/date-type",
  "JavaScript/disable-body-scrolling",
  "JavaScript/es2015-classes",
  "JavaScript/es2015",
  "JavaScript/es6-generators",
  "JavaScript/event-bubbling",
  "JavaScript/event-delegation",
  "JavaScript/event-target-vs-currunttarget",
  "JavaScript/event",
  "JavaScript/graph-ql",
  "JavaScript/indexeddb",
  "JavaScript/javascript-assign-function-without-run",
  "JavaScript/javascript-codeschool",
  "JavaScript/javascript-design-pattern",
  "JavaScript/javascript-download-from-get-url",
  "JavaScript/javascript-run-function",
  "JavaScript/javascript-switch-with-regex",
  "JavaScript/javascript-template-handlebar",
  "JavaScript/javascript-tips",
  "JavaScript/javascript-unlock",
  "JavaScript/jpub-ajax-json",
  "JavaScript/jquery-plugin",
  "JavaScript/js-unit-test",
  "JavaScript/map",
  "JavaScript/meteor",
  "JavaScript/mobile-web",
  "JavaScript/okky-conference",
  "JavaScript/print-page",
  "JavaScript/promise",
  "JavaScript/prototype",
  "JavaScript/reference-type",
  "JavaScript/regular-expression",
  "JavaScript/short-circuit",
  "JavaScript/sparse-array-vs-dense-array",
  "JavaScript/udemy-react",
  "JavaScript/udemy-vue",
  "JavaScript/vuejs",
  "JavaScript/way-to-get-javascript-in-html",
  "JavaScript/bugs-in-ios8",
  "JavaScript/functional-programming",
  "JavaScript/functional-programming-with-lodash-fp",
  "JavaScript/typescript",
  "JavaScript/plz-answer",
];

exports.DailyCodingList = [
  "Daily-Coding/191120-two-sum",
  "Daily-Coding/191119-remove-duplicates-from-sorted-array",
  "Daily-Coding/180110-recursion-davis-staircase",
  "Daily-Coding/180110-stacks",
  "Daily-Coding/array-helpers",
  "Daily-Coding/banner-sorting",
  "Daily-Coding/christmas-tree",
  "Daily-Coding/codewars-170922-factorial-tail",
  "Daily-Coding/counting-duplicates",
  "Daily-Coding/dc-171106-two-sum",
  "Daily-Coding/find-the-divisors",
  "Daily-Coding/get-random-number",
  "Daily-Coding/haming-numbers",
  "Daily-Coding/hello-what",
  "Daily-Coding/human-readable-time",
  "Daily-Coding/ip-validation",
  "Daily-Coding/javascript-round-floor-ceil",
  "Daily-Coding/moving-zeros-to-the-end",
  "Daily-Coding/numerology",
  "Daily-Coding/ordinal-numbers",
  "Daily-Coding/pick-peaks",
  "Daily-Coding/points-on-a-line",
  "Daily-Coding/power-of-two",
  "Daily-Coding/prefill-an-array",
  "Daily-Coding/return-substring-instance-count",
  "Daily-Coding/reverse-string-in-array",
  "Daily-Coding/square-matrix-multiplication",
  "Daily-Coding/sum-by-factors",
  "Daily-Coding/the-shell-game",
  "Daily-Coding/unique-in-order",
];

exports.ReactList = [
  "React/next-js.md",
  "React/react-ts-storybook.md",
  "React/flux",
  "React/react-testing",
  "React/react",
  "React/redux-saga",
  "React/redux",
  "React/hook",
  "React/render-props",
  "React/high-order-component",
  "React/react-component",
  "React/context",
];

exports.AngularList = [
  "Angular/angularjs-moment-filter",
  "Angular/angularjs",
  "Angular/api",
];

exports.JsTestingList = [
  "Javascript-Testing/casperjs",
  "Javascript-Testing/passing-arguments-with-casperjs",
  "Javascript-Testing/trouble-shooting",
];

exports.CSSList = [
  "CSS/100-percent-height-colums-fixed-sidebar-with-pure-css",
  "CSS/css-block-inline-block-vertical-align",
  "CSS/css-overlay",
  "CSS/css-property-order",
  "CSS/emmet",
  "CSS/flexbox",
  "CSS/flickering-css-transition",
  "CSS/make-border-smaller-than-div-length",
  "CSS/markup-level-test",
  "CSS/nth-child-vs-nth-of-type",
  "CSS/web-font",
  "CSS/styled-components",
];

exports.GoogleAnalyticsList = [
  "Google-Analytics/GA-tag-manager",
  "Google-Analytics/data-analytics",
  "Google-Analytics/ecommerce-in-google-analytics-and-tagmanager",
  "Google-Analytics/ecommerce-in-google-analytics",
  "Google-Analytics/enhanced-ecommerce-in-google-analytics",
  "Google-Analytics/enhanced-ecommerce-in-tagmanager",
  "Google-Analytics/google-analytics-data-layer",
  "Google-Analytics/google-analytics-terminology",
  "Google-Analytics/google-analytics",
  "Google-Analytics/make-multiple-categories-in-ga",
  "Google-Analytics/Gaekoboard_guide",
];

exports.DataStructureAndAlgorithmList = [
  "Data-structure-and-Algorithm/khan-algorithm",
];
exports.DjangoList = [
  "Django/digging-into-django",
  "Django/django-aggregation",
  "Django/django-bower-grunt",
  "Django/django-cache",
  "Django/django-migration-conflict",
  "Django/django-models",
  "Django/django-pinkfong-tv",
  "Django/django-queries",
  "Django/django-resize-image",
  "Django/django-seperate-settings-and-secret-file",
  "Django/django-social-auth-add-profile-page",
  "Django/django-social-auth",
  "Django/django-url",
  "Django/django",
  "Django/djnago-admin",
  "Django/extend-django-user-model",
  "Django/how-to-response-template-in-django",
  "Django/pass-data-through-redirect-in-django",
  "Django/react-with-django-rest-framework",
  "Django/two-scoops-of-django",
];
exports.ETCList = [
  "ETC/amplitude",
  "ETC/beer",
  "ETC/readable-code",
  "ETC/2015-sanfrancisco-tour",
  "ETC/2017_NDC",
  "ETC/Gaekoboard_guide",
  "ETC/Markdown-Cheatsheet",
  "ETC/atom",
  "ETC/computer-graphics",
  "ETC/cool-stuff",
  "ETC/cross-browsing-with-pow",
  "ETC/daily-commit",
  "ETC/dash-vs-underscore",
  "ETC/eclipse-shortcut",
  "ETC/english-in-programming",
  "ETC/fundamentals-of-design-codeschool",
  "ETC/google-apps-201",
  "ETC/grid-layout",
  "ETC/heroku",
  "ETC/intellij-shortcut",
  "ETC/naver-deview-2015",
  "ETC/network",
  "ETC/node-easymock",
  "ETC/nodejs",
  "ETC/operation-system",
  "ETC/productivity",
  "ETC/pycharm-shortcut",
  "ETC/pycon-2015",
  "ETC/zendesk",
  "ETC/chrome-extension",
  "ETC/TIL",
  "ETC/vs-code",
  "ETC/swift-basic",
  "ETC/swift_doc",
  "ETC/career-ladders",
  "ETC/becoming-senior",
];
exports.GitList = [
  "Git/git-guide",
  "Git/git-ignore",
  "Git/git-reverse-commit",
  "Git/pro-git",
  "Git/rebase-with-sourcetree",
  "Git/trouble-shooting-on-console",
  "Git/rebase-vs-merge-commit",
  "Git/revert-certain-file",
];
exports.BundlerList = ["Bundler/grunt", "Bundler/webpack"];

exports.MarkUpList = [
  "Markup/icon-font",
  "Markup/HTML5-2015-next",
  "Markup/HTML5",
  "Markup/RWD",
  "Markup/css-animation",
  "Markup/css",
  "Markup/delete-inline-block-unexpected-gap",
  "Markup/html-label-mdn-translation",
  "Markup/html5-boilerplate",
  "Markup/interactive-web-design",
  "Markup/responsive-iframe-embed",
  "Markup/scrolling-error-in-ios-when-fixed-element-focus",
  "Markup/svg",
  "Markup/wsconf-2016",
  "Markup/youtube-thumbnail-crop",
];
exports.NetworkList = ["Network/ssh-tunneling"];
exports.PythonList = [
  "Python/make-hobbycoding",
  "Python/make-jaystagram",
  "Python/python-set-environments",
  "Python/python-startkit",
  "Python/python",
];

exports.DevOpsList = ["DevOps/docker.md", "DevOps/vupress-github-actions.md"];

exports.MILList = [
  "MIL/mil-2108.md",
  "MIL/mil-2107.md",
  "MIL/mil-2106.md",
  "MIL/mil-2106.md",
  "MIL/mil-2104.md",
  "MIL/mil-2103.md",
  "MIL/mil-2102.md",
  "MIL/mil-2101.md",
  "MIL/mil-2011-2012.md",
  "MIL/mil-2010.md",
  "MIL/mil-2009.md",
  "MIL/mil-2008.md",
  "MIL/mil-1911.md",
];

exports.BooksList = [
  "Books/책조각들",
  "Books/210926-lean-anlytics",
  "Books/210727-일주일은-금요일부터-시작하라",
  "Books/210516-자기만의방",
  "Books/210515-아무튼달리기",
  "Books/210514-아무튼술",
  "Books/210312-적게자도괜찮습니다",
  "Books/210220-가짜감정",
  "Books/210210-feedforward",
  "Books/210120-radical-candor",
  "Books/210101-clean-code",
  "Books/210122-1일1명상1평온.md",
];
